routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::group(['middleware' => ['auth']], function () {
    //CRUD Kategori
    Route::resource('kategori', 'kategoricontroller');

    //Profil
    Route::resource('profil', 'ProfilController')->only([
        'index', 'update'
    ]);

    //CRUDPeminjaman
    Route::resource('peminjaman', 'PeminjamanController');
});

// CRUD BUKU
Route::resource('buku', 'BukuController');

Auth::routes();

Route::get('/test-dompdf', function(){
    $pdf = App::make('dompdf.wrapper');
    $pdf->loadHTML('<h1>Hello World</h1>');
    return $pdf->stream();
});

app/Kategori.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Kategori extends Model
{
    protected $table = "kategori";
    protected $fillable = ['nama'];

    public $timestamps = false;


    public function buku()
    {
    return $this->hasMany('App\Buku');
    }  

}

app/Http/Controllers/kategoricontroller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use RealRashid\SweetAlert\Facades\Alert;
use Illuminate\Support\Facades\DB;
use App\Kategori;

class kategoricontroller extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $kategori = DB::table('kategori')->get();

        return view('dashboard.kategori.index', compact('kategori'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.kategori.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'nama' => 'required|unique:kategori,nama|max:255',
        ],
        [
            'nama.required' => 'tidak boleh kosong',
        ]);

        DB::table('kategori')->insert(
            [
                'nama' => $request['nama'], 
            ]
            );
        
        Alert::success('Berhasil', 'Berhasil menambah kategori baru');
        return redirect('/kategori');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $kategori = kategori::findorfail($id);
        return view('dashboard.kategori.show', compact('kategori'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $kategori = DB::table('kategori')->where('id', $id)->first();
        return view('dashboard.kategori.edit', compact('kategori'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'nama' => 'required|max:255',
            
        ],
        [
            'nama.required' => 'tidak boleh kosong',
            
        ]);

            DB::table('kategori')
              ->where('id', $id)
              ->update(
                    [
                      'nama' => $request['nama'],
                    
                    ]
                );
                return redirect('/kategori');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        DB::table('kategori')->where('id', '=', $id)->delete();
        return redirect('/kategori');
    }
}

resources/views/dashboard/kategori/create.blade.php
@extends('layouts.master')

@section('title')
   Tambah Kategori Buku
@endsection

@section('content')

<form action="/kategori" method="POST">
    @csrf
    <div class="form-group">
        <label for="nama">Nama</label>
        <input type="text" class="form-control" name="nama" id="nama" placeholder="Masukkan Nama Kategori">
        @error('nama')
            <div class="alert alert-danger">
                {{ $message }}
            </div>
        @enderror
    </div>
    <button type="submit" class="btn btn-primary">Tambah</button>
</form>
@endsection

resources/views/dashboard/kategori/edit.blade.php
@extends('layouts.master')

@section('title')
   Edit kategori {{$kategori->nama}}
@endsection

@section('content')

<form action="/kategori/{{$kategori->id}}" method="POST">
    @csrf
    @method('put')
    <div class="form-group">
        <label for="nama">Nama</label>
        <input type="text" value="{{$kategori->nama}}" class="form-control" name="nama" id="nama" placeholder="Masukkan Nama Kategori">
        @error('nama')
            <div class="alert alert-danger">
                {{ $message }}
            </div>
        @enderror
    </div>
    <button type="submit" class="btn btn-success">Update</button>
</form>
@endsection

resources/views/dashboard/kategori/index.blade.php
@extends('layouts.master')

@section('title')
   List Kategori
@endsection

@section('content')

<a href="/kategori/create" class="btn btn-success btn-sm my-2">Tambah</a>

<table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Nama</th>
      </tr>
    </thead>
    <tbody>
      @forelse ($kategori as $key=> $item)
          <tr>
              <td>{{$key + 1 }}</td>
              <td>{{$item->nama}}</td>
              <td>
                <form action="/kategori/{{$item->id}}" method="post">
                  @csrf
                  @method('delete')
                    <a href="/kategori/{{$item->id}}" class="btn btn-primary btn-sm">Detail</a>
                    <a href="/kategori/{{$item->id}}/edit" class="btn btn-success btn-sm">Edit</a>
                    <input type="submit" class="btn btn-danger btn-sm" value="delete">
                  </form>
              </td>
          </tr>
      @empty
          <tr>
              <td>Data tidak ditemukan</td>
          </tr>
      @endforelse
    </tbody>
  </table>
@endsection

resources/views/dashboard/kategori/show.blade.php
@extends('layouts.master')

@section('title')
   List kategori {{$kategori->nama}}
@endsection

@section('content')
    {{-- <h1>{{$kategori->nama}}</h1> --}}
    {{-- <p>{{$kategori->nama}}</p> --}}

    @forelse ($kategori->buku as $item)
    <div class="col-4">
        <div class="card">
          <img class="card-img-top" src="{{asset('image/'.$item->thumbnail)}}" height="10%" width="30%" alt="">
          <div class="card-body">
            <h5>{{$item->nama}}</h5>
              <span class="badge badge-info">{{$item->kategori->nama}}</span>
              <p class="card-text">{{ Str::limit($item->deskripsi, 100) }}</p>
                  <a href="{{route('buku.show', $item->id)}}" class="btn btn-primary btn-sm">Detail</a>
          </div>
        </div>
    </div>
    @empty
        <p>Tidak ada buku di kategori ini</p>
    @endforelse

@endsection