routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::group(['middleware' => ['auth']], function () {
    //CRUD Kategori
    Route::resource('kategori', 'kategoricontroller');

    //Profil
    Route::resource('profil', 'ProfilController')->only([
        'index', 'update'
    ]);

    //CRUDPeminjaman
    Route::resource('peminjaman', 'PeminjamanController');
});

// CRUD BUKU
Route::resource('buku', 'BukuController');

Auth::routes();

Route::get('/test-dompdf', function(){
    $pdf = App::make('dompdf.wrapper');
    $pdf->loadHTML('<h1>Hello World</h1>');
    return $pdf->stream();
});

app/Buku.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Buku extends Model
{
    protected $table = "buku";

    protected $fillable = ['thumbnail', 'nama', 'deskripsi', 'tahun', 'penerbit', 'pengarang', 'kategori_id'];
    // 
    public function kategori()
    {
      return $this->belongsTo('App\Kategori','kategori_id');
    }

    public function peminjaman()
    {
        return $this->hasMany('App\Peminjaman');
    }
  
}

app/Http/Controllers/BukuController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

// use Illuminate\Support\Facades\DB;

use App\Buku;
use App\Kategori;
use File;

class BukuController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth')->except('index','show');
    }

    public function create()
    {
        $kategori = Kategori::all();

        return view('dashboard.buku.create', compact('kategori'));
    }

    public function store(Request $request)
    {
        $request->validate([
            'thumbnail' => 'mimes:png,jpg,jpeg',
            'nama' => 'required|max:255',
            'deskripsi' => 'required',
            'tahun' => 'required',
            'penerbit' => 'required',
            'pengarang' => 'required',
            'kategori_id' => 'required',
        ]);

        $fileName = time().'.'.$request->thumbnail->extension();
        
        $kategori = new Buku;
        $kategori->thumbnail = $fileName;
        $kategori->nama = $request->nama;
        $kategori->deskripsi = $request->deskripsi;
        $kategori->tahun = $request->tahun;
        $kategori->penerbit = $request->penerbit;
        $kategori->pengarang = $request->pengarang;
        $kategori->kategori_id = $request->kategori_id;
    
        $kategori->save();

        $request->thumbnail->move(public_path('image'), $fileName);
        
        return redirect('/buku');
    }

    public function index()
    {
        $buku = Buku::all();

        return view('dashboard.buku.index', compact('buku'));
    }

    public function show($id)
    {
        $buku = Buku::findorfail($id);

        return view('dashboard.buku.show', compact('buku'));
    }

    public function edit($id)
    {
        $kategori = Kategori::all();
        $buku = Buku::findorfail($id);
        return view('dashboard.buku.edit', compact('buku', 'kategori'));
    }

    public function update(Request $request, $id)
    {
        $request->validate([
            'thumbnail' => 'required|mimes:png,jpg,jpeg',
            'nama' => 'required|max:255',
            'deskripsi' => 'required',
            'tahun' => 'required',
            'penerbit' => 'required',
            'pengarang' => 'required',
            'kategori_id' => 'required',
        ]);

        $buku = Buku::findorfail($id);
        // $post->delete();
        if($request->has('thumbnail')){
            $path = "image/";
            File::delete($path . $buku->thumbnail);
            $fileName = time().'.'.$request->thumbnail->extension();

            $request->thumbnail->move(public_path('image'), $fileName);

            $buku_data = [
                'thumbnail' => $fileName,
                'nama' => $request->nama,
                'deskripsi' => $request->deskripsi,
                'tahun' => $request->tahun,
                'penerbit' => $request->penerbit,
                'pengarang' => $request->pengarang,
                'kategori_id' => $request->kategori_id,
            ];
        } else{
            $buku_data = [
                'nama' => $request->nama,
                'deskripsi' => $request->deskripsi,
                'tahun' => $request->tahun,
                'penerbit' => $request->penerbit,
                'pengarang' => $request->pengarang,
                'kategori_id' => $request->kategori_id,
            ];
        }

        $buku->update($buku_data);

        return redirect('/buku');
    }

    public function destroy($id)
    {
        $buku = Buku::findorfail($id);
        $path = "image/";
        File::delete($path . $buku->thumbnail);
        $buku->delete();

        return redirect('/buku');

    }
}

resources/views/dashboard/buku/create.blade.php
@extends('layouts.master')

@section('title')
   Tambah Buku
@endsection

@section('content')

    <form action="/buku" method="POST" enctype="multipart/form-data">
        @csrf
        <div class="form-group">
            <label>Thumbnail</label><br> 
            <input type="file" class="form-control" name="thumbnail">
            @error('thumbnail')
                <div class="alert alert-danger">
                    {{ $message }}
                </div>
            @enderror
        </div>
        <div class="form-group">
            <label> Nama </label>
            <input type="text" class="form-control" name="nama" placeholder="Masukkan Nama Buku">
            @error('nama')
                <div class="alert alert-danger">
                    {{ $message }}
                </div>
            @enderror
        </div>
        <div class="form-group">
            <label> Deskrispi </label>
            <textarea name="deskripsi" class="form-control" cols="30" rows="10"></textarea>
            @error('deskripsi')
                <div class="alert alert-danger">
                    {{ $message }}
                </div>
            @enderror
        </div>
        <div class="form-group">
            <label> Tahun </label>
            <input type="text" class="form-control" name="tahun" placeholder="Masukkan Tahun">
            @error('tahun')
                <div class="alert alert-danger">
                    {{ $message }}
                </div>
            @enderror
        </div>
        <div class="form-group">
            <label> Penerbit </label>
            <input type="text" class="form-control" name="penerbit" placeholder="Masukkan Nama Penerbit">
            @error('penerbit')
                <div class="alert alert-danger">
                    {{ $message }}
                </div>
            @enderror
        </div>
        <div class="form-group">
            <label> Pengarang </label>
            <input type="text" class="form-control" name="pengarang" placeholder="Masukkan Nama Pengarang">
            @error('pengarang')
                <div class="alert alert-danger">
                    {{ $message }}
                </div>
            @enderror
        </div>
        <div class="form-group">
            <label> Kategori </label>
            <select name="kategori_id" class="form-control" id="">
                <option value="">----Pilih Kategori---</option>
                @foreach ($kategori as $item)
                    <option value="{{$item->id}}">{{$item->nama}}</option> 
                @endforeach
            </select>
            @error('kategori_id')
                <div class="alert alert-danger">
                    {{ $message }}
                </div>
            @enderror
        </div>
        

        <button type="submit" class="btn btn-primary">Tambah</button>
    </form>
    
@endsection

resources/views/dashboard/buku/edit.blade.php
@extends('layouts.master')

@section('title')
   Edit Buku
@endsection

@section('content')

    <form action="/buku/{{$buku->id}}" method="POST" enctype="multipart/form-data">
        @csrf
        @method('put')
        <div class="form-group">
            <label>Thumbnail</label><br> 
            <input type="file" class="form-control" value="{{$buku->thumbnail}}" name="thumbnail">
            @error('thumbnail')
                <div class="alert alert-danger">
                    {{ $message }}
                </div>
            @enderror
        </div>
        <div class="form-group">
            <label> Nama </label>
            <input type="text" class="form-control" value="{{$buku->nama}}"name="nama" placeholder="Masukkan Nama Buku">
            @error('nama')
                <div class="alert alert-danger">
                    {{ $message }}
                </div>
            @enderror
        </div>
        <div class="form-group">
            <label> Deskrispi </label>
            <textarea name="deskripsi" class="form-control" cols="30" rows="10">{{$buku->deskripsi}}</textarea>
            @error('deskripsi')
                <div class="alert alert-danger">
                    {{ $message }}
                </div>
            @enderror
        </div>
        <div class="form-group">
            <label> Tahun </label>
            <input type="text" class="form-control" value="{{$buku->tahun}}"name="tahun" placeholder="Masukkan Tahun">
            @error('tahun')
                <div class="alert alert-danger">
                    {{ $message }}
                </div>
            @enderror
        </div>
        <div class="form-group">
            <label> Penerbit </label>
            <input type="text" class="form-control" value="{{$buku->penerbit}}"name="penerbit" placeholder="Masukkan Nama Penerbit">
            @error('penerbit')
                <div class="alert alert-danger">
                    {{ $message }}
                </div>
            @enderror
        </div>
        <div class="form-group">
            <label> Pengarang </label>
            <input type="text" class="form-control" value="{{$buku->pengarang}}" name="pengarang" placeholder="Masukkan Nama Pengarang">
            @error('pengarang')
                <div class="alert alert-danger">
                    {{ $message }}
                </div>
            @enderror
        </div>
        <div class="form-group">
            <label> Kategori </label>
            <select name="kategori_id" class="form-control" id="">
                <option value="">----Pilih Kategori---</option>
                @foreach ($kategori as $item)
                    @if ($item->id === $buku->kategori_id)
                        <option value="{{$item->id}}" selected>{{$item->nama}}</option> 
                    @else
                        <option value="{{$item->id}}">{{$item->nama}}</option>
                    @endif
                    
                @endforeach
            </select>
            @error('kategori_id')
                <div class="alert alert-danger">
                    {{ $message }}
                </div>
            @enderror
        </div>
        
        
        <button type="submit" class="btn btn-primary"> Update </button>
    </form>

@endsection

resources/views/dashboard/buku/index.blade.php
@extends('layouts.master')

@section('title')
   List Buku
@endsection

@section('content')

@auth
  <a href="/buku/create" class="btn btn-success btn-sm my-2">Tambah Buku</a>   
@endauth


<div class="row">
  @forelse ($buku as $item)
      <div class="col-4">
        <div class="card">
          <img class="card-img-top" src="{{asset('image/'.$item->thumbnail)}}" height="10%" width="30%" alt="">
          <div class="card-body">
            <h5>{{$item->nama}}</h5>
              <span class="badge badge-info">{{$item->kategori->nama}}</span>
              <p class="card-text">{{ Str::limit($item->deskripsi, 100) }}</p>
              @auth
                <form action="{{route('buku.destroy', $item->id)}}" method="POST">
                  @csrf
                  @method('delete')

                  <a href="{{route('buku.show', $item->id)}}" class="btn btn-primary btn-sm">Detail</a>
                <a href="{{route('buku.edit', $item->id)}}" class="btn btn-warning btn-sm">Edit</a>
                <input type="submit" class="btn btn-danger btn-sm" value="Delete">
                </form> 
              @endauth
              @guest
                <a href="{{route('buku.show', $item->id)}}" class="btn btn-primary btn-sm">Detail</a>
              @endguest
          </div>
        </div>
      </div>
  @empty
      <h1> Tidak ada Buku yang ditemukan</h1>
  @endforelse
</div>
@endsection

@push('scripts')
  <script>
    Swal.fire({
        title: "Berhasil!",
        text: "Memasangkan script sweet alert",
        icon: "success",
        confirmButtonText: "Cool",
    });
  </script>
@endpush

resources/views/dashboard/buku/show.blade.php
@extends('layouts.master')

@section('title')
   Halaman Detail Buku 
@endsection

@section('content')
    <img src="{{asset('image/'.$buku->thumbnail)}}" width="200px" alt="">
    <h2 class="text-primary">{{$buku->nama}}</h4>
    <p>{{$buku->deskripsi}}</p>
    <p> Tahun : {{$buku->tahun}}</p>
    <p> Penerbit : {{$buku->penerbit}}</p>
    <p> Pengarang : {{$buku->pengarang}}</p>
    
@endsection